fix: Circular import bug
- Addresses the following error message that would appear on directly
  importing the package:

  ```
  ImportError: cannot import name 'LazyCommandInterface' from partially initialized module 'libqtile.lazy' (most likely due to a circular import) (/usr/lib/python3.10/site-packages/libqtile/lazy.py)
  ````